<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF2mIPD8\KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF2mIPD8/KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF2mIPD8.legacy');

    return;
}

if (!\class_exists(KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF2mIPD8\KernelDevDebugContainer::class, KernelDevDebugContainer::class, false);
}

return new \ContainerF2mIPD8\KernelDevDebugContainer([
    'container.build_hash' => 'F2mIPD8',
    'container.build_id' => '82bae3ec',
    'container.build_time' => 1774874239,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF2mIPD8');
