<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGKZEmXW\KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGKZEmXW/KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGKZEmXW.legacy');

    return;
}

if (!\class_exists(KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGKZEmXW\KernelDevDebugContainer::class, KernelDevDebugContainer::class, false);
}

return new \ContainerGKZEmXW\KernelDevDebugContainer([
    'container.build_hash' => 'GKZEmXW',
    'container.build_id' => '8af1a58c',
    'container.build_time' => 1774870823,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGKZEmXW');
